#include "FileUtil.hh"
ConfigFile::Token1 ConfigFile::transition[256] = {
  END,   CTRL,  CTRL, CTRL, CTRL, CTRL, CTRL, CTRL,  // C-@ C-a C-b C-c C-d C-e C-f C-g
  CTRL,  SPACE, LINE, CTRL, CTRL, LINE, CTRL, CTRL,  // C-h TAB \n C-k C-l \r C-n C-o
  CTRL,  CTRL,  CTRL, CTRL, CTRL, CTRL, CTRL, CTRL,  // C-p C-q C-r C-s C-t C-u C-v C-w
  CTRL,  CTRL,  CTRL, CTRL, CTRL, CTRL, CTRL, CTRL,  // C-x C-y C-z .. ESC stuff
  SPACE, PUNC,  PUNC, COMMENT,  PUNC, PUNC, PUNC, PUNC,  // ' ', ! " # $ % & '
  OPAREN, CPAREN, PUNC, PUNC, PUNC, PUNC, PUNC, PUNC,    // * + , - . / 
  DIGIT, DIGIT, DIGIT, DIGIT, DIGIT, DIGIT, DIGIT, DIGIT, // 0 1 2 3 4 5 6 7
  DIGIT, DIGIT, PUNC, PUNC, PUNC, PUNC, PUNC, PUNC,       // 8 9 : ; < = > ?
  PUNC,  UPPER, UPPER, UPPER, UPPER, UPPER, UPPER, UPPER, // @ A B C D E F G
  UPPER, UPPER, UPPER, UPPER, UPPER, UPPER, UPPER, UPPER, // H I J K L M N O
  UPPER, UPPER, UPPER, UPPER, UPPER, UPPER, UPPER, UPPER, // P Q R S T U V W
  UPPER, UPPER, UPPER, OBRACK, PUNC, CBRACK, PUNC, IDENT, // X Y Z [ \ ] ^ _
  PUNC, LOWER, LOWER, LOWER, LOWER, LOWER, LOWER, LOWER,  // ` a b c d e f g
  LOWER, LOWER, LOWER, LOWER, LOWER, LOWER, LOWER, LOWER,  // h i j k l m n o
  LOWER, LOWER, LOWER, LOWER, LOWER, LOWER, LOWER, LOWER,  // p q r s t u v w
  LOWER, LOWER, LOWER, OCURLY, PUNC, CCURLY, PUNC, CTRL,  // x y z { | } ~ del
  CTRL,  CTRL,  CTRL, CTRL, CTRL, CTRL, CTRL, CTRL,
  CTRL,  CTRL,  CTRL, CTRL, CTRL, CTRL, CTRL, CTRL,
  CTRL,  CTRL,  CTRL, CTRL, CTRL, CTRL, CTRL, CTRL,
  CTRL,  CTRL,  CTRL, CTRL, CTRL, CTRL, CTRL, CTRL,
  CTRL,  CTRL,  CTRL, CTRL, CTRL, CTRL, CTRL, CTRL,
  CTRL,  CTRL,  CTRL, CTRL, CTRL, CTRL, CTRL, CTRL,
  CTRL,  CTRL,  CTRL, CTRL, CTRL, CTRL, CTRL, CTRL,
  CTRL,  CTRL,  CTRL, CTRL, CTRL, CTRL, CTRL, CTRL
};
