OPT=
DEBUG=-g

testfileutil: testfileutil.cc FileUtil.hh FileUtil.cc Makefile
	g++ $(DEBUG) $(OPT) testfileutil.cc FileUtil.cc -o testfileutil


teststringbuf: teststringbuf.cc StringBuffer.hh GrowArray.hh
	g++ -g -O2 teststringbuf.cc -o teststringbuf

