-*- mode: compilation; default-directory: "d:/git/EE553-CPP/buildingprograms/simplemake/" -*-
Compilation started at Fri Dec  7 12:32:55

make -k 
g++ Main.cc Account.cc -o banking

Compilation finished at Fri Dec  7 12:32:56
