#
#
#
#COMPILE	=	g++ $(DEBUG)
DEBUG	:= -g
OPT	:= #-O2
CXX	:= g++
COMPILE	:= $(CXX) $(DEBUG) $(OPT)

banking:	Main.o Account.o
	$(COMPILE) Main.o Account.o -o banking

Main.o:	Main.cc Account.hh
	$(COMPILE) -c Main.cc

Account.o: Account.cc Account.hh
	$(COMPILE) -c Account.cc

clean:
	rm *.o *.exe

