#
# This makefile will build each object file independently
# Changing one line in a cc file should only require one file to be compiled
# then all are linked together
#

banking:	Main.o Account.o
	g++ Main.o Account.o -o banking

Main.o:	Main.cc Account.hh
	g++ -c Main.cc

Account.o: Account.cc Account.hh
	g++ -c Account.cc

clean:
	rm *.o *.exe

